//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADM {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SADM.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string HudContineDefault {
            get {
                return ResourceManager.GetString("HudContineDefault", resourceCulture);
            }
        }
        
        public static string LoginLoading {
            get {
                return ResourceManager.GetString("LoginLoading", resourceCulture);
            }
        }
        
        public static string PasswordRecoveryLoading {
            get {
                return ResourceManager.GetString("PasswordRecoveryLoading", resourceCulture);
            }
        }
        
        public static string PasswordRecoverySuccessful {
            get {
                return ResourceManager.GetString("PasswordRecoverySuccessful", resourceCulture);
            }
        }
        
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        public static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        public static string RemindMe {
            get {
                return ResourceManager.GetString("RemindMe", resourceCulture);
            }
        }
        
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        public static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        public static string SecondLastNamePlaceholder {
            get {
                return ResourceManager.GetString("SecondLastNamePlaceholder", resourceCulture);
            }
        }
        
        public static string StreetPlaceholder {
            get {
                return ResourceManager.GetString("StreetPlaceholder", resourceCulture);
            }
        }
        
        public static string NumberPlaceholder {
            get {
                return ResourceManager.GetString("NumberPlaceholder", resourceCulture);
            }
        }
        
        public static string ColonyPlaceholder {
            get {
                return ResourceManager.GetString("ColonyPlaceholder", resourceCulture);
            }
        }
        
        public static string CityPlaceholder {
            get {
                return ResourceManager.GetString("CityPlaceholder", resourceCulture);
            }
        }
        
        public static string StatePlaceholder {
            get {
                return ResourceManager.GetString("StatePlaceholder", resourceCulture);
            }
        }
        
        public static string CellPhonePlaceholder {
            get {
                return ResourceManager.GetString("CellPhonePlaceholder", resourceCulture);
            }
        }
        
        public static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        public static string ZipCodePlaceholder {
            get {
                return ResourceManager.GetString("ZipCodePlaceholder", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string QuestionPlaceholder {
            get {
                return ResourceManager.GetString("QuestionPlaceholder", resourceCulture);
            }
        }
        
        public static string AnswerPlaceholder {
            get {
                return ResourceManager.GetString("AnswerPlaceholder", resourceCulture);
            }
        }
        
        public static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        public static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        public static string NameInvalid {
            get {
                return ResourceManager.GetString("NameInvalid", resourceCulture);
            }
        }
        
        public static string FirstNameEmpty {
            get {
                return ResourceManager.GetString("FirstNameEmpty", resourceCulture);
            }
        }
        
        public static string FirstNameInvalid {
            get {
                return ResourceManager.GetString("FirstNameInvalid", resourceCulture);
            }
        }
        
        public static string PhoneNumberEmpty {
            get {
                return ResourceManager.GetString("PhoneNumberEmpty", resourceCulture);
            }
        }
        
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        public static string ZipCodeEmpty {
            get {
                return ResourceManager.GetString("ZipCodeEmpty", resourceCulture);
            }
        }
        
        public static string ZipCodeInvalid {
            get {
                return ResourceManager.GetString("ZipCodeInvalid", resourceCulture);
            }
        }
        
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        public static string ErrorItem {
            get {
                return ResourceManager.GetString("ErrorItem", resourceCulture);
            }
        }
        
        public static string PhoneHelp {
            get {
                return ResourceManager.GetString("PhoneHelp", resourceCulture);
            }
        }
        
        public static string PasswordHelp {
            get {
                return ResourceManager.GetString("PasswordHelp", resourceCulture);
            }
        }
        
        public static string PasswordConfirmHelp {
            get {
                return ResourceManager.GetString("PasswordConfirmHelp", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsFirstPart {
            get {
                return ResourceManager.GetString("TermsAndConditionsFirstPart", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsSecondPart {
            get {
                return ResourceManager.GetString("TermsAndConditionsSecondPart", resourceCulture);
            }
        }
        
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        public static string SignUpLoading {
            get {
                return ResourceManager.GetString("SignUpLoading", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsError {
            get {
                return ResourceManager.GetString("TermsAndConditionsError", resourceCulture);
            }
        }
        
        public static string PrivacityTitle {
            get {
                return ResourceManager.GetString("PrivacityTitle", resourceCulture);
            }
        }
        
        public static string PrivacityText {
            get {
                return ResourceManager.GetString("PrivacityText", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsTitle", resourceCulture);
            }
        }
        
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsText {
            get {
                return ResourceManager.GetString("TermsAndConditionsText", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        public static string QuestionRequired {
            get {
                return ResourceManager.GetString("QuestionRequired", resourceCulture);
            }
        }
        
        public static string AnswerRequired {
            get {
                return ResourceManager.GetString("AnswerRequired", resourceCulture);
            }
        }
        
        public static string AssociateContractTitle {
            get {
                return ResourceManager.GetString("AssociateContractTitle", resourceCulture);
            }
        }
        
        public static string NisLabel {
            get {
                return ResourceManager.GetString("NisLabel", resourceCulture);
            }
        }
        
        public static string NisHelp {
            get {
                return ResourceManager.GetString("NisHelp", resourceCulture);
            }
        }
        
        public static string NisPlaceholder {
            get {
                return ResourceManager.GetString("NisPlaceholder", resourceCulture);
            }
        }
        
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        public static string PreviousReadingPlaceholder {
            get {
                return ResourceManager.GetString("PreviousReadingPlaceholder", resourceCulture);
            }
        }
        
        public static string AssociateContractButton {
            get {
                return ResourceManager.GetString("AssociateContractButton", resourceCulture);
            }
        }
        
        public static string BalancesTitle {
            get {
                return ResourceManager.GetString("BalancesTitle", resourceCulture);
            }
        }
        
        public static string Colony {
            get {
                return ResourceManager.GetString("Colony", resourceCulture);
            }
        }
        
        public static string BalanceLabel {
            get {
                return ResourceManager.GetString("BalanceLabel", resourceCulture);
            }
        }
        
        public static string ExpireLabel {
            get {
                return ResourceManager.GetString("ExpireLabel", resourceCulture);
            }
        }
        
        public static string NisSimpleLabel {
            get {
                return ResourceManager.GetString("NisSimpleLabel", resourceCulture);
            }
        }
        
        public static string NirRequired {
            get {
                return ResourceManager.GetString("NirRequired", resourceCulture);
            }
        }
        
        public static string NisInvalid {
            get {
                return ResourceManager.GetString("NisInvalid", resourceCulture);
            }
        }
        
        public static string PreviousReadingEmpty {
            get {
                return ResourceManager.GetString("PreviousReadingEmpty", resourceCulture);
            }
        }
        
        public static string PreviousReadingInvalid {
            get {
                return ResourceManager.GetString("PreviousReadingInvalid", resourceCulture);
            }
        }
        
        public static string AssociateContractLoading {
            get {
                return ResourceManager.GetString("AssociateContractLoading", resourceCulture);
            }
        }
        
        public static string TotalToPay {
            get {
                return ResourceManager.GetString("TotalToPay", resourceCulture);
            }
        }
        
        public static string OutstandingDebt {
            get {
                return ResourceManager.GetString("OutstandingDebt", resourceCulture);
            }
        }
        
        public static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        public static string BilledMonth {
            get {
                return ResourceManager.GetString("BilledMonth", resourceCulture);
            }
        }
        
        public static string PeriodOfConsumption {
            get {
                return ResourceManager.GetString("PeriodOfConsumption", resourceCulture);
            }
        }
        
        public static string BalanceButton {
            get {
                return ResourceManager.GetString("BalanceButton", resourceCulture);
            }
        }
        
        public static string DeleteBalanceButton {
            get {
                return ResourceManager.GetString("DeleteBalanceButton", resourceCulture);
            }
        }
        
        public static string DeleteBalanceTitle {
            get {
                return ResourceManager.GetString("DeleteBalanceTitle", resourceCulture);
            }
        }
        
        public static string DeleteBalanceMessage {
            get {
                return ResourceManager.GetString("DeleteBalanceMessage", resourceCulture);
            }
        }
        
        public static string RecoverPasswordTitle {
            get {
                return ResourceManager.GetString("RecoverPasswordTitle", resourceCulture);
            }
        }
        
        public static string RecoverPasswordMessage {
            get {
                return ResourceManager.GetString("RecoverPasswordMessage", resourceCulture);
            }
        }
        
        public static string SuccessRecoverPasswordMessage {
            get {
                return ResourceManager.GetString("SuccessRecoverPasswordMessage", resourceCulture);
            }
        }
        
        public static string SendingRecoverPasswordMessage {
            get {
                return ResourceManager.GetString("SendingRecoverPasswordMessage", resourceCulture);
            }
        }
        
        public static string BalanceTitle {
            get {
                return ResourceManager.GetString("BalanceTitle", resourceCulture);
            }
        }
        
        public static string MenuMyData {
            get {
                return ResourceManager.GetString("MenuMyData", resourceCulture);
            }
        }
        
        public static string MenuMyBalances {
            get {
                return ResourceManager.GetString("MenuMyBalances", resourceCulture);
            }
        }
        
        public static string MenuBills {
            get {
                return ResourceManager.GetString("MenuBills", resourceCulture);
            }
        }
        
        public static string MenuReports {
            get {
                return ResourceManager.GetString("MenuReports", resourceCulture);
            }
        }
        
        public static string MenuPaymentCenter {
            get {
                return ResourceManager.GetString("MenuPaymentCenter", resourceCulture);
            }
        }
        
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        public static string MenuCloseSession {
            get {
                return ResourceManager.GetString("MenuCloseSession", resourceCulture);
            }
        }
        
        public static string MyDataTitle {
            get {
                return ResourceManager.GetString("MyDataTitle", resourceCulture);
            }
        }
        
        public static string DownloadBillButton {
            get {
                return ResourceManager.GetString("DownloadBillButton", resourceCulture);
            }
        }
        
        public static string SendToTheAddress {
            get {
                return ResourceManager.GetString("SendToTheAddress", resourceCulture);
            }
        }
        
        public static string SendToEmail {
            get {
                return ResourceManager.GetString("SendToEmail", resourceCulture);
            }
        }
        
        public static string BillsTitle {
            get {
                return ResourceManager.GetString("BillsTitle", resourceCulture);
            }
        }
        
        public static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        public static string CallButton {
            get {
                return ResourceManager.GetString("CallButton", resourceCulture);
            }
        }
        
        public static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        public static string GenerateReportDesciption {
            get {
                return ResourceManager.GetString("GenerateReportDesciption", resourceCulture);
            }
        }
        
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        public static string RequestStatusDescription {
            get {
                return ResourceManager.GetString("RequestStatusDescription", resourceCulture);
            }
        }
        
        public static string MyRequestListTitle {
            get {
                return ResourceManager.GetString("MyRequestListTitle", resourceCulture);
            }
        }
        
        public static string GenerateReportTitle {
            get {
                return ResourceManager.GetString("GenerateReportTitle", resourceCulture);
            }
        }
        
        public static string Measurer {
            get {
                return ResourceManager.GetString("Measurer", resourceCulture);
            }
        }
        
        public static string PreviousReading {
            get {
                return ResourceManager.GetString("PreviousReading", resourceCulture);
            }
        }
        
        public static string LastReading {
            get {
                return ResourceManager.GetString("LastReading", resourceCulture);
            }
        }
        
        public static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        public static string SeeMoreButton {
            get {
                return ResourceManager.GetString("SeeMoreButton", resourceCulture);
            }
        }
        
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        public static string SubjectLabel {
            get {
                return ResourceManager.GetString("SubjectLabel", resourceCulture);
            }
        }
        
        public static string SubjectPlaceholder {
            get {
                return ResourceManager.GetString("SubjectPlaceholder", resourceCulture);
            }
        }
        
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        public static string MailLabel {
            get {
                return ResourceManager.GetString("MailLabel", resourceCulture);
            }
        }
        
        public static string MailPlaceholder {
            get {
                return ResourceManager.GetString("MailPlaceholder", resourceCulture);
            }
        }
        
        public static string DraftingLabel {
            get {
                return ResourceManager.GetString("DraftingLabel", resourceCulture);
            }
        }
        
        public static string DraftingPlaceholder {
            get {
                return ResourceManager.GetString("DraftingPlaceholder", resourceCulture);
            }
        }
        
        public static string PaymentCenterList {
            get {
                return ResourceManager.GetString("PaymentCenterList", resourceCulture);
            }
        }
        
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        public static string CloseSessionTitle {
            get {
                return ResourceManager.GetString("CloseSessionTitle", resourceCulture);
            }
        }
        
        public static string CloseSessionMessage {
            get {
                return ResourceManager.GetString("CloseSessionMessage", resourceCulture);
            }
        }
        
        public static string CloseSessionAcceptButton {
            get {
                return ResourceManager.GetString("CloseSessionAcceptButton", resourceCulture);
            }
        }
        
        public static string CloseSessionCancelButton {
            get {
                return ResourceManager.GetString("CloseSessionCancelButton", resourceCulture);
            }
        }
        
        public static string PayTitle {
            get {
                return ResourceManager.GetString("PayTitle", resourceCulture);
            }
        }
        
        public static string CardHolderPlaceholder {
            get {
                return ResourceManager.GetString("CardHolderPlaceholder", resourceCulture);
            }
        }
        
        public static string CardNumberPlaceholder {
            get {
                return ResourceManager.GetString("CardNumberPlaceholder", resourceCulture);
            }
        }
        
        public static string CvvPlaceholder {
            get {
                return ResourceManager.GetString("CvvPlaceholder", resourceCulture);
            }
        }
        
        public static string CvvHelp {
            get {
                return ResourceManager.GetString("CvvHelp", resourceCulture);
            }
        }
        
        public static string MonthPlaceholder {
            get {
                return ResourceManager.GetString("MonthPlaceholder", resourceCulture);
            }
        }
        
        public static string YearPlaceholder {
            get {
                return ResourceManager.GetString("YearPlaceholder", resourceCulture);
            }
        }
        
        public static string PayButton {
            get {
                return ResourceManager.GetString("PayButton", resourceCulture);
            }
        }
        
        public static string CardHolderInvalid {
            get {
                return ResourceManager.GetString("CardHolderInvalid", resourceCulture);
            }
        }
        
        public static string CardNumberInvalid {
            get {
                return ResourceManager.GetString("CardNumberInvalid", resourceCulture);
            }
        }
        
        public static string CvvInvalid {
            get {
                return ResourceManager.GetString("CvvInvalid", resourceCulture);
            }
        }
        
        public static string CardHolderEmpty {
            get {
                return ResourceManager.GetString("CardHolderEmpty", resourceCulture);
            }
        }
        
        public static string CardNumberEmpty {
            get {
                return ResourceManager.GetString("CardNumberEmpty", resourceCulture);
            }
        }
        
        public static string CvvEmpty {
            get {
                return ResourceManager.GetString("CvvEmpty", resourceCulture);
            }
        }
        
        public static string MonthEmpty {
            get {
                return ResourceManager.GetString("MonthEmpty", resourceCulture);
            }
        }
        
        public static string YearEmpty {
            get {
                return ResourceManager.GetString("YearEmpty", resourceCulture);
            }
        }
        
        public static string NisFormat {
            get {
                return ResourceManager.GetString("NisFormat", resourceCulture);
            }
        }
        
        public static string BillMonthYearFormat {
            get {
                return ResourceManager.GetString("BillMonthYearFormat", resourceCulture);
            }
        }
        
        public static string NisListTitle {
            get {
                return ResourceManager.GetString("NisListTitle", resourceCulture);
            }
        }
        
        public static string ReportTypeListTitle {
            get {
                return ResourceManager.GetString("ReportTypeListTitle", resourceCulture);
            }
        }
        
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        public static string FugueInMyAddress {
            get {
                return ResourceManager.GetString("FugueInMyAddress", resourceCulture);
            }
        }
        
        public static string FugueInAnotherAddress {
            get {
                return ResourceManager.GetString("FugueInAnotherAddress", resourceCulture);
            }
        }
        
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        public static string ScanBarcode {
            get {
                return ResourceManager.GetString("ScanBarcode", resourceCulture);
            }
        }
        
        public static string AddContract {
            get {
                return ResourceManager.GetString("AddContract", resourceCulture);
            }
        }
        
        public static string AddContractLoading {
            get {
                return ResourceManager.GetString("AddContractLoading", resourceCulture);
            }
        }
        
        public static string DeleteContractLoading {
            get {
                return ResourceManager.GetString("DeleteContractLoading", resourceCulture);
            }
        }
        
        public static string UpdateDataLoading {
            get {
                return ResourceManager.GetString("UpdateDataLoading", resourceCulture);
            }
        }
        
        public static string UpdateDataButton {
            get {
                return ResourceManager.GetString("UpdateDataButton", resourceCulture);
            }
        }
        
        public static string UpdateDataSuccess {
            get {
                return ResourceManager.GetString("UpdateDataSuccess", resourceCulture);
            }
        }
        
        public static string UpdateDataUnchanged {
            get {
                return ResourceManager.GetString("UpdateDataUnchanged", resourceCulture);
            }
        }
        
        public static string AddReportLoading {
            get {
                return ResourceManager.GetString("AddReportLoading", resourceCulture);
            }
        }
        
        public static string AddReportSuccess {
            get {
                return ResourceManager.GetString("AddReportSuccess", resourceCulture);
            }
        }
    }
}
